services:
  moodle:
    container_name: moodle_develop
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4000:80'
    networks:
      web_net:
        aliases:
          - web_net
    volumes:
      - logs:/var/log/apache2/
      - ./:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always
volumes:
  logs:
networks:
  web_net:
    name: moodle_net
    external: true # Parece que tu contenedor moodle_develop ha arrancado correctamente, aunque te muestra una advertencia sobre la red moodle_net, ya que esta red ya existe pero no fue creada como parte de este proyecto.