services:
  moodle:
    container_name: moodle_develop
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '4000:80'
    volumes:
      - logs:/var/log/apache2/
      - ./:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    restart: always

volumes:
  logs:

    